Properly indent loop body
License: MIT
Signed-off-by: Christian Couder <chriscool@tuxfamily.org>

diff --git a/git-push-each b/git-push-each
--- a/git-push-each
+++ b/git-push-each
@@ -82,10 +82,10 @@ if [ $clean -eq 1 ]; then
 	spec="($prefix[0-9a-fA-F]{40})"
 	for line in $(git branch -r | egrep -wo "$remote/$spec" | egrep -o "$spec")
 	do
-	echo "git push $remote :$line"
-	if [ $dryrun -eq 0 ]; then
-		git push "$remote" ":$line" || die "Could not git push '$remote' ':$line'"
-	fi
+		echo "git push $remote :$line"
+		if [ $dryrun -eq 0 ]; then
+			git push "$remote" ":$line" || die "Could not git push '$remote' ':$line'"
+		fi
 	done
 	exit 0
 fi
