Use temp file when cleaning
This makes it possible to check that "git branch -r" worked.

License: MIT
Signed-off-by: Christian Couder <chriscool@tuxfamily.org>

diff --git a/git-push-each b/git-push-each
--- a/git-push-each
+++ b/git-push-each
@@ -80,13 +80,16 @@ test -n "$prefix" || die "Empty <branch-prefix> argument\n$usage"
 # clean up mode
 if [ $clean -eq 1 ]; then
 	spec="($prefix[0-9a-fA-F]{40})"
-	for line in $(git branch -r | egrep -wo "$remote/$spec" | egrep -o "$spec")
+	temp=$(mktemp) || die "mktemp failed"
+	git branch -r >"$temp" || die "Could not list remote branches"
+	for line in $(egrep -wo "$remote/$spec" "$temp" | egrep -o "$spec")
 	do
 		echo "git push $remote :$line"
 		if [ $dryrun -eq 0 ]; then
 			git push "$remote" ":$line" || die "Could not git push '$remote' ':$line'"
 		fi
 	done
+	rm "$temp"
 	exit 0
 fi
 
