mkdir templte (otherwise fails on osx)

diff --git a/git-push-each b/git-push-each
--- a/git-push-each
+++ b/git-push-each
@@ -83,7 +83,7 @@ test -n "$prefix" || die "Empty <branch-prefix> argument\n$usage"
 # clean up mode
 if [ $clean -eq 1 ]; then
 	spec="($prefix[0-9a-fA-F]{40})"
-	temp=$(mktemp) || die "mktemp failed"
+	temp=$(mktemp -t gpe-XXXX-) || die "mktemp failed"
 	git branch -r >"$temp" || die "Could not list remote branches"
 	for line in $(egrep -wo "$remote/$spec" "$temp" | egrep -o "$spec")
 	do
