Check that git push succeeds
License: MIT
Signed-off-by: Christian Couder <chriscool@tuxfamily.org>

diff --git a/git-push-each b/git-push-each
--- a/git-push-each
+++ b/git-push-each
@@ -84,7 +84,7 @@ if [ $clean -eq 1 ]; then
 	do
 	echo "git push $remote :$line"
 	if [ $dryrun -eq 0 ]; then
-		git push "$remote" ":$line"
+		git push "$remote" ":$line" || die "Could not git push '$remote' ':$line'"
 	fi
 	done
 	exit 0
@@ -96,6 +96,6 @@ do
 	spec="$line:refs/heads/$prefix$line"
 	echo "git push $remote $spec"
 	if [ $dryrun -eq 0 ]; then
-		git push "$remote" "$spec"
+		git push "$remote" "$spec" || die "Could not git push '$remote' '$spec'"
 	fi
 done
